routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('formlogin');
});
Route::get('/formlogin','AuthController@formlogin')->name('login');
Route::post('/postlogin','AuthController@postlogin');
Route::get('/login_personal','PersonalAuthController@login_personal')->name('login');
Route::post('/postloginpersonal','PersonalAuthController@postloginpersonal');
Route::get('/formregister','AuthController@formregister');
Route::get('/logout','AuthController@logout');


Route::get('postulant','postulantController@index');



Route::group(['middleware' => ['auth','CheckLevel:Admin']],function(){

  Route::get('/home', 'HomeController@index')->name('home');
  
  Route::get('/assets/trash','AssetsController@trash');
  Route::get('/assets/restore/{id}','AssetsController@restore');
  Route::get('/assets/deleted_permanent/{id}','AssetsController@deleted_permanent');
  Route::get('/assets/restore_all','AssetsController@restore_all');
  Route::get('/assets/deleted_all','AssetsController@deleted_all');
  Route::get('/assets/{asset}/transaksi','AssetsController@transaksi');
  Route::patch('/transaksi/{asset}','AssetsController@transaksi');
  Route::post('/transaksi','AssetsController@input_transaksi');
  Route::Resource('assets', 'AssetsController');

  //karyawan
  Route::Resource('employees', 'EmployeesController');
  
  Route::get('/karyawanresign','EmployeesController@resign');

  //Cuti Admin
   //Data Pengajuan Cuti
  Route::get('/cuti/trash','CutiController@trash');
  Route::get('/cuti/restore/{id}','CutiController@restore');
  Route::get('/cuti/deleted_permanent/{id}','CutiController@deleted_permanent');
  Route::get('/cuti/restore_all','CutiController@restore_all');
  Route::get('/cuti/deleted_all','CutiController@deleted_all');
  Route::get('/cuti/{cuti}/detil','CutiController@detil');
  Route::Resource('cuti','CutiController');
    //Kategori Cuti
  Route::get('/category/trash','CategoryController@trash');
  Route::get('/category/restore/{category}','CategoryController@restore');
  Route::get('/category/deleted_permanent/{category}','CategoryController@deleted_permanent');
  Route::get('/category/restore_all','CategoryController@restore_all');
  Route::get('/category/deleted_all','CategoryController@deleted_all');
  Route::delete('/category/{category}','CategoryController@destroy');        
  Route::Resource('category','CategoryController');        

  //gaji

 //kelola manajemen
    //jabatan
    Route::get('/jabatan/trash','JabatanController@trash');
    Route::get('/jabatan/restore/{position}','JabatanController@restore');
    Route::get('/jabatan/deleted_permanent/{position}','JabatanController@deleted_permanent');
    Route::get('/jabatan/restore_all','JabatanController@restore_all');
    Route::get('/jabatan/deleted_all','JabatanController@deleted_all');
    Route::delete('/jabatan/{position}','JabatanController@destroy');
    Route::Resource('jabatan','JabatanController');
  
      //divisi
    Route::get('/divisi/trash','DivisionController@trash');
    Route::get('/divisi/restore/{division}','DivisionController@restore');
    Route::get('/divisi/deleted_permanent/{division}','DivisionController@deleted_permanent');
    Route::get('/divisi/restore_all','DivisionController@restore_all');
    Route::get('/divisi/deleted_all','DivisionController@deleted_all');
    Route::delete('/divisi/{division}','DivisionController@destroy');
    Route::Resource('divisi','DivisionController');
      
      //corporate_group
    Route::get('/corporate/trash','CorporateGroupController@trash');
    Route::get('/corporate/restore/{corporate}','CorporateGroupController@restore');
    Route::get('/corporate/deleted_permanent/{corporate}','CorporateGroupController@deleted_permanent');
    Route::get('/corporate/restore_all','CorporateGroupController@restore_all');
    Route::get('/corporate/deleted_all','CorporateGroupController@deleted_all');
    Route::delete('/corporate/{corporate}','CorporateGroupController@destroy');
    Route::Resource('corporate','CorporateGroupController');
      
      //grade
    Route::get('/grade/trash','GradeController@trash');
    Route::get('/grade/restore/{grade}','GradeController@restore');
    Route::get('/grade/deleted_permanent/{grade}','GradeController@deleted_permanent');
    Route::get('/grade/restore_all','GradeController@restore_all');
    Route::get('/grade/deleted_all','GradeController@deleted_all');
    Route::delete('/grade/{grade}','GradeController@destroy');
    Route::Resource('grade','GradeController');
});






  Route::group(['middleware' => ['auth','CheckLevel:Admin,Pegawai,Atasan,Direktur']],function(){
  Route::get('/admin','AdminController@dashboard');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');






Route::group(['middleware' => ['auth','CheckLevel:Pegawai']],function(){

  Route::get('/home', 'HomeController@index')->name('home');

  Route::Resource('cutipegawai','CutiPegawaiController');
  Route::get('/cutipegawai/{cuti}/detil','CutiPegawaiController@detil');
});

Route::group(['middleware' => ['auth','CheckLevel:Atasan']],function(){

  Route::get('/home', 'HomeController@index')->name('home');

  Route::Resource('cuti_atasan','CutiAtasanController');
  Route::get('/cuti_atasan/{cuti}/detil','CutiAtasanController@detil');

  Route::get('persetujuan_atasan','CutiController@persetujuanatasan');
  Route::get('/persetujuan_atasan/{cuti}/detil','CutiController@detilatasan');
  Route::get('/persetujuan_atasan/{cuti}/edit','CutiController@editatasan');
  Route::patch('/persetujuan_atasan/{cuti}', 'CutiController@updateatasan');
});

Route::group(['middleware' => ['auth','CheckLevel:Direktur']],function(){

  Route::get('/home', 'HomeController@index')->name('home');

  
  
  Route::get('persetujuan_direktur','CutiController@persetujuandirektur');
  Route::get('/persetujuan_direktur/{cuti}/detil','CutiController@detildirektur');
  Route::get('/persetujuan_direktur/{cuti}/edit','CutiController@editdirektur');
  Route::patch('/persetujuan_direktur/{cuti}', 'CutiController@updatedirektur');
});

app/Corporate.php
<?php

namespace App;

use DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Corporate extends Model
{
    use SoftDeletes;
    protected $table = "corporate_groups";
    protected $fillable = ['kode_corporate_group', 'nama_corporate_group'];
}

resources/views/admin/corporate/index.blade.php
@extends('layouts.master')

@section('content')
<div class="page-title">
              <div class="title_left">
                <h3>PT Davinti Indonesia</h3>
              </div>

              <!-- <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-secondary" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div> -->
            </div>
<div class="col-md-12 col-sm-12 ">
  <div class="x_panel">
    <div class="x_title">
      <h2>Daftar Corporate</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Settings 1</a>
              <a class="dropdown-item" href="#">Settings 2</a>
          </div>
        </li> 
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li> -->
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <div class="row">
            <div class="col-sm-12">
              <div class="card-box table-responsive">
      <p class="text-muted font-13 m-b-30">
          <a href="" class="btn btn-custon-four btn-primary" data-toggle="modal" data-target="#modalTambahCorporate"><i class="fa fa-reply"></i> Tambah Corporate</a>
          <a href="corporate/trash" class="btn btn-custon-four btn-warning"><i class="fa fa-refresh fa-spin fa-fw"></i> Dapatkan Data Terhapus</a>
          @if (session('status'))
          <div class="alert alert-success alert-dismissible " role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <strong>SUKSES !!!</strong> Data Corporate Berhasil Ditambahkan.
          </div>
          @endif

          @if (session('edit'))
          <div class="alert alert-warning alert-dismissible " role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <strong>SUKSES !!!</strong> Data Corporate Berhasil Diubah.
          </div>
          @endif

          @if (session('delete'))
          <div class="alert alert-danger alert-dismissible " role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <strong>SUKSES !!!</strong> Data Corporate Berhasil Dihapus.
          </div>
          @endif
      </p>
      <table id="datatable-fixed-header" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>No</th>
            <th>Kode Corporate</th>
            <th>Nama Corporate</th>
            <th>Aksi</th>
          </tr>
        </thead>


        <tbody>
          @foreach ($corporate_groups as $v => $corporate )
          <tr>
            <td>{{$loop -> iteration}}</td>
            <td>{{$corporate -> kode_corporate_group}}</td>
            <td>{{$corporate -> nama_corporate_group}}</td>
            <td>
                <a href="/corporate" class="btn btn-custon-four btn-warning" data-myidcor="{{$corporate -> id}}" data-mykodecor="{{$corporate -> kode_corporate_group}}" data-mynamacor="{{$corporate -> nama_corporate_group}}" data-toggle="modal" data-target="#modalEditCorporate">Ubah</a>
                <form action="/corporate/{{$corporate->id}}" method="post" class="d-inline">
                @method('DELETE')
                @csrf
                <button type="submit" class="btn btn-custon-four btn-danger" onclick="return confirm('Apakah Anda Yakin Untuk Mengahpus Data Ini?')" >Hapus</button>
                </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>
  </div>
</div>


<!-- --------- MODAL --------- -->

    <!-- --------- MODAL TAMBAH --------- -->
                  <div class="modal fade" id="modalTambahCorporate" tabindex="-1" role="dialog" aria-labelledby="modalTambahTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                      <form id="formSave" method="POST" action="/corporate">
                        
                        <div class="modal-header">
                          <h5 class="modal-title" id="modalTambahTitle">Tambah Divisi Baru</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>                        
                          <div class="modal-body">                        
                            @csrf
                            <div class="form-group">
                                  <label for="kode">Kode Corporate</label>
                                  <input type="text" name="kodeDiv" disabled class="form-control" placeholder="Automatic Generate">
                            </div>

                            <div class="form-group">
                                  <label for="nama">Nama Corporate</label>
                                  <input type="text" class="form-control @error('namaCor') is-invalid @enderror" name="namaCor" placeholder="Masukan Nama Jabatan Baru" value ="{{ old('namaCor')}}">
                                  @error('namaCor')
                                    <div class="invalid-feedback">Kolom Ini Tidak Boleh Kosong</div>
                                  @enderror
                            </div>
                          </div>                        
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal" id = "closeModalTambah" >Tutup</button>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                        </form>
                      </div>
                    </div>
                  </div>
    <!-- --------- END MODAL TAMBAH --------- -->

    <!-- --------- MODAL EDIT --------- -->
    <div class="modal fade" id="modalEditCorporate" tabindex="-1" role="dialog" aria-labelledby="modalEditTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                      <form action="{{route('corporate.update', 'test')}}" id="editForm" method="post">
                      @method('patch')
                      @csrf
                        <div class="modal-header">
                          <h5 class="modal-title" id="modalEditTitle">Edit Data Corporate</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>

                          
                          <div class="modal-body" id="editCorporate">
                              <input type="hidden" name="idcorporate" id="idcor" value="">
                              
                              <div class="form-group">
                                <label for="kode">Kode Corporate</label>
                                <input type="text" disabled class="form-control" id="kodecor" name="kodeCor" value="">                              
                              </div>

                              <div class="form-group">
                                <label for="kode">Nama Corporate</label>
                                <input type="text" class="form-control @error('namaCor') is-invalid @enderror" id="namacor" name="namaCor" placeholder="Masukan Nama Jabatan Baru" value ="{{ old('namaCor')}}">
                                    @error('namaCor')
                                      <div class="invalid-feedback">Kolom Ini Tidak Boleh Kosong</div>
                                    @enderror
                              </div>
                          </div>

                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                        </form>
                      </div>
                    </div>
                  </div>
    <!-- --------- END MODAL EDIT --------- -->

@endsection

resources/views/admin/corporate/trash.blade.php
@extends('layouts.master')

@section('content')
<div class="page-title">
              <div class="title_left">
                <h3>PT Davinti Indonesia</h3>
              </div>

              <!-- <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-secondary" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div> -->
            </div>
<div class="col-md-12 col-sm-12 ">
  <div class="x_panel">
    <div class="x_title">
      <h2>Daftar Data Corporate Group Terhapus</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Settings 1</a>
              <a class="dropdown-item" href="#">Settings 2</a>
          </div>
        </li> 
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li> -->
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <div class="row">
            <div class="col-sm-12">
              <div class="card-box table-responsive">
      <p class="text-muted font-13 m-b-30">
        <a href="/corporate" class="btn btn-outline-secondary"> << Kembali</a>
        <a href="/corporate/restore_all" onclick="return confirm('Apakah Anda Yakin Untuk Mengembalikan Semua Data Terhapus?')" class="btn btn-custon-four btn-primary"><i class="fa fa-refresh fa-spin fa-fw"></i> Pulihkan Semua Data</a>
        <a href="/corporate/deleted_all" onclick="return confirm('Apakah Anda Yakin Untuk Menghapus Secara Permanen Semua Data Ini?')" class="btn btn-custon-four btn-danger"><i class="fa fa-trash"></i> Hapus Semua Data</a>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible " role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>SUKSES !!!</strong> Data Corporate Group Berhasil Ditambahkan.
        </div>
        @endif

        @if (session('edit'))
        <div class="alert alert-warning alert-dismissible " role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>SUKSES !!!</strong> Data Corporate Group Berhasil Diubah.
        </div>
        @endif

        @if (session('delete'))
        <div class="alert alert-danger alert-dismissible " role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>SUKSES !!!</strong> Data Corporate Group Berhasil Dihapus.
        </div>
        @endif
      </p>
      <table id="datatable-fixed-header" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>No</th>
            <th>Kode Corporate Group</th>
            <th>Nama Corporate Group</th>
            <th>Tanggal Ditambahkan</th>
            <th>Tanggal Dihapus</th>
            <th>Aksi</th>
          </tr>
        </thead>


        <tbody>
          @foreach ($corporates  as $corporate )
          <tr>
            <td>{{$loop -> iteration}}</td>
            <td>{{$corporate -> kode_corporate_group}}</td>
            <td>{{$corporate -> nama_corporate_group}}</td>
            <td>{{$corporate -> created_at}}</td>
            <td>{{$corporate -> deleted_at}}</td>
            <td>
              <a href="/corporate/restore/{{$corporate->id}}" onclick="return confirm('Apakah Anda Yakin Untuk Mengembalikan Data Ini?')" class="btn btn-custon-four btn-success">Pulihkan Data</a>
              <a href="/corporate/deleted_permanent/{{$corporate->id}}" onclick="return confirm('Apakah Anda Yakin Untuk Menghapus Secara Permanen Data ini?')" class="btn btn-custon-four btn-danger">Hapus Data</a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>
  </div>
</div>

@endsection